name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
      git submodule update --init --recursive
      ./scripts/patch.sh
      docker build . --file Dockerfile --tag MSVBASE:$(date +%s)
